# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0309ba6e330183318d767e7db3873043d5699a3b1fed3a150576ab30d864ffa63b78b078b678123b3f8663ff790798f3b6f0d530c3c9572145000754a6475a20

test:
  secret_key_base: 121c08b6ef6df52788c7eddf9d6319eab6e23339def1997f8aa6a42e5741620d0c64a08fa49d9e1216ed61381594a1412a0ae1ad82eb9000ac6c3414b656632f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
